title: letroglodyte # name of the site
author: eltroglodyto # name of site's author
email: andre@publikey.ch # email of site's author
url: https://letroglodyte.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed) 
  <p> 
    <br> hi, i'm andré. i graduated in 2017 with a master's degree in information systems from hec lausanne. <br> i co-founded in 2021 a software company called <a href="https://publikey.ch">publikey</a>.
    <br> i'm currently working those cool projects : <br> an offline due diligence and compliance ai agent for the company<a href="https://inv3nt.ch/">inv3nt</a> <br> a <a href="https://canary.wakweli.com">proof of democracy protocol</a>. 
    <br> <br> i like : <span id="like"></span>.
    <br> <br> i tend to avoid : <span id="avoid"></span>.<br> 
  </p>

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # make all titles lowercase
sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true