title: letroglodyte # name of the site
author: eltroglodyto # name of site's author
email: andre@publikey.ch # email of site's author
url: https://letroglodyte.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed) 
  <p> 
    <br> i'm professional pixel's dealer. i co-founded a software company called <a href="https://publikey.ch">publikey<a/>.
    <br> i'm currently working on cool projects like an offline due diligence and compliance ai agent or a <a href="https://canary.wakweli.com">proof of democracy protocol</a>. 
    <br> <br> i'm into : computers (specially the imac g3), sci-fi / mystery / horror books, all kinds of music, touching grass, updates and science in general.
    <br> <br> i tend to avoid : super extroverts, rust (all kinds), night clubs and curious bears.<br> 
  </p>

permalink: /:slug.html

favicon: "favicon.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true